name: Test
run-name: Test - ${{ github.head_ref || github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: make init
      - run: make lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: make init

      - name: Run tests
        run: |
          make test